### ISSUE TITLE
Remove Need For Environment Variables?

### ISSUE THREAD

**Issue by alexhulbert** [Mic92/nix-ld#26]
Hi! What if nix-ld.c inspected the PT_LOAD segments put into RAM by the ELF handler in order to get a list of shared objects required by the binary being run, used nix-index to find suitable packages that provide those libraries, and then used `lib.makeLibraryPath` on those packages to compute the correct value for NIX_LD_LIBRARY_PATH automatically?

Would this work??? I want to attempt this myself but I don't know how I would go about debugging additional code that I write for this project. What does your dev environment for working on nix-ld look like?

I have so many packages that run in various types of env-dropping sandboxes (which seems to be an issue for other people including @contrun from issue #17) and something like this would make my life single-booting NixOS so much more convenient. Also, it would be really nice to be able to run foreign executables without having to use tools like nix-alien and nix-autobahn.

Thanks so much

**Comment by Mic92** [comment]
I would actually not go down this route for the following reasons:

1. I don't think this would give you all the libraries needed.  More complex executables often load own libraries that bring in more dependencies. In which case `nix-ld` would need to re-implement all of the library search and load mechanism of glibc in a bug compatible way. 

2. It might also significantly slow-down. As it now spawns `nix-index` on every executable and than download the packages, which could be for some use cases quite slow and require unexpected network access. 

3. Also the linked package in `nix-index` could be outdated or even in incorrect. When using nix-index I often see unrelated electron applications that vendor a certain library and come in the search index before the actual library. So without implementing a ranking this would suddenly turn into a lottery what is going to be downloaded & executed.

That's why I think having a configuration file (could be even locked up in the current or parent folders instead of a fixed path), would be a better approach. Than people could use arbitrary automation to find the right libraries, that than can be cached and does not lead to surprises and hard to debug behavior.

**Comment by alexhulbert** [comment]
Ah I see. That makes a lot of sense. Thanks for your quick response.
